/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'developer' at '8/9/17 1:55 PM' with Gradle 2.14.1
 *
 * @author developer, @date 8/9/17 1:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
